language: python

python:
  - 3.6.8
  - 3.7

services:
  - docker

before_script:
  - docker run --name postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=markov -p 0.0.0.0:5432:5432 -d postgres
  - export PG_HOST=localhost

script:
  - docker build -t markov-chain-text-editor .